$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:2
        },
        768:{
            items:6
        },
        1200:{
            items:9
        }
    }
});